#!/usr/bin/env ruby
# frozen_string_literal: true

# require 'bolt'
require 'bolt/cli'
require 'bolt/error'

cli = Bolt::CLI.new(ARGV)
begin
  opts = cli.parse
  exitcode = cli.execute(opts)
  exit exitcode
rescue Bolt::CLIExit
  exit
rescue Bolt::Error => e
  exit e.error_code
end
